server:
  port: ${SERVER_PORT}
spring:
  application:
    name: gym-pro
  datasource:
    url: jdbc:postgresql://${HOST_DB}:${PORT_DB}/${DB_NAME}
    username: ${USER_DB}
    password: ${PASSWORD_DB}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          create_namespaces: true
