server:
  port: ${SERVER_PORT}
spring:
  application:
    name: gym-pro
  datasource:
    url: jdbc:postgresql://${HOST_DB}:${PORT_DB}/${DB_NAME}
    username: ${USER_DB}
    password: ${PASSWORD_DB}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          create_namespaces: true
  mail:
    host: mail.sitiapp.com
    port: 587
    username: ${EMAIL}
    password: ${PASSWORD_EMAIL}
    properties:
      mail.smtp:
#        ssl.trust: smtp.gmail.com
        auth: true
        starttls.enable: true

sms:
  base-api-url: ${SMS_API_BASE_URL}
  auth-username: ${SMS_API_USERNAME}
  auth-password: ${SMS_API_PASSWORD}
#google:
#  mail:
#    client:
#      id: ${CLIENT_ID}
#      secret: ${CLIENT_ID_SECRET}
# refresh.token: